skip_tags: true

cache: C:\Users\appveyor\.gradle

build_script:
- ps: ./gradlew.bat build

artifacts:
- path: build\libs\*.jar

deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: DiscordRP v$(appveyor_build_version)
  auth_token:
    secure: LmSz3gy+ZuwqfOo/ezDfu2lz4IHsjmw/Wi/CggfLrSKNV+5tjGFuwsx31G1iLWg9
  on:
    branch: master

for:
-
  # Release builds
  branches:
    only:
      - master

  after_deploy:
  - ps: ./gradlew.bat curseforge

-
  branches:
    except:
      - master

  environment:
    VERSION_CLS: dev